### ISSUE TITLE
ansible-navigator missing new `pull: arguments: []` entry

### ISSUE THREAD

**Issue by cidrblock** [ansible/schemas#150]
See below for PR

**Comment by ssbarnea** [comment]
Please include a snippet of the new format, it would help implementing it. Also I am not keen on keeping the old names into the schema, which means that we should not update the schema until navigator is releasing the new options.

For those reasons, i do think that probably breaking change in config is not the best idea, why not keeping it flat and avoid breakages?

**Comment by cidrblock** [comment]
https://github.com/ansible/ansible-navigator/pull/952/files#diff-6f6404dd95a867f6f66e0daf73b8d59403264099647b1e6804203532a39d63deR45

We'll do a major release.  It's still early days for navigator so better now than later.

**Comment by ssbarnea** [comment]
Ansible navigator schema is not part of navigator project itself.
