### ISSUE TITLE
Correct galaxy/AAP namespace and collection name patterns

### ISSUE THREAD

**Issue by apatard** [ansible/schemas#285]
While working on https://github.com/ansible/schemas/pull/284, found out that:
```
"pattern": "^[a-z][a-z0-9_]+$",
```
will not generate a pattern error with an invalid string. This pattern will:
```
"pattern": "^[a-z][a-z0-9_]+$",
```

Not sure exactly the reason of this but if this is a real problem and not a local one, some other places will need fixing:
```
git grep -rw pattern f/ | egrep -v '"\^'
f/ansible-galaxy.json:      "pattern": "[a-z][a-z0-9_]+",
f/ansible-galaxy.json:      "pattern": "[a-z][a-z0-9_]+",
f/ansible-meta.json:          "pattern": "[a-z0-9][a-z0-9_]+",
f/ansible-meta.json:          "pattern": "[a-z][a-z0-9_]+",
```

So, some fixing may be needed and also some tests files are needed to caught this.

**Comment by ssbarnea** [comment]
@apatard Do you have any example of namespace or collection that starts with a number from galaxy? My impression was that number was not allowed as prefix, just like in python identifiers.

A link to official allowed patterns would also help.

**Comment by apatard** [comment]
damn. now, I see a typo in my BR, *months* after writing it. My point was not about the filtering but how the pattern is written:
some (all?) tools used to check the schema seems to properly match things only with proper string start '^' and end characters '$'. 
The first example should rather be:
```
"pattern": "[a-z][a-z0-9_]+",
```
So my bug report was about:
- is this really the case ?
- if so, we should  change all patterns detected to use ``^....$``. Then, would this break stuff ?
- are we missing some proper testing since this possible problem was not detected ?
