### ISSUE TITLE
Some tasks parameter of the type integer does not allow vars

### ISSUE THREAD

**Issue by timo-fc** [ansible/schemas#298]
Hi,
some tasks parameter of the type integer does not allow vars.
currently this is valid:

    - name: "Run a command async"
      command: "test_command.sh"
      async: 20
      poll: "{{ test_var }}"

currently this is not valid:

    - name: "Run a command async"
      command: "test_command.sh"
      async: "{{ test_var }}"
      poll: 2
  
If I understand is right `"type": "integer"` would need to be replaced with `"$ref": "#/$defs/templated-integer"` for all task values.

I do not know if there is a reason for not allowing vars in those cases.

**Comment by carlosmmatos** [comment]
I'm having the same issue with the `delay` tasks [param](https://github.com/ansible/schemas/blob/1b7e1d39720347dc0b0122174b08f913b9108788/f/ansible-tasks.json#L307), where I'm using a variable for the integer.
