### ISSUE TITLE
Allow serial to be templated integer

### ISSUE THREAD

**Issue by mjonasz** [ansible/schemas#328]
Similar to https://github.com/ansible/schemas/pull/290

I would like to use templates for `serial` parameter in playbooks.

Currently `ansible-lint` do not allow this:
```
serial: '{{ some_variable_passed_by_extra_vars }}"
```

`ansible-lint` output:
```
schema: '{{ some_variable_passed_by_extra_vars | default(1) | int }}' is not of type 'integer' (schema[playbook])
playbooks/some_playbook.yml:1  Returned errors will not include exact line numbers, but they will mention
the schema name being used as a tag, like ``playbook-schema``,
``tasks-schema``.
```

Ansible itself allow such playbook to run without problems.

```
ansible-lint --version
ansible-lint 6.2.1 using ansible 2.12.6
```

Thanks in advance!

**Comment by ssbarnea** [comment]
@mjonasz True. Can you make a PR to address it?
