### ISSUE TITLE
Root schema is missing `items` field

### ISSUE THREAD

**Issue by zach-source** [ansible/schemas#330]
I recently was playing with some jsonschema using the latest ansible.json file and noticed that validation wasn't occuring properly. Inspecting the schema I noticed the lack of root items. I believe this PR was improperly made https://github.com/ansible/schemas/pull/230 and should be reverted. 

I've added a few pics of some testing I did in https://www.jsonschemavalidator.net/

Test with [old schema](https://raw.githubusercontent.com/ansible/schemas/b4db55a727bfe625efed4eaf132f4a7f96c30f69/f/ansible.json)
![with_old_schema](https://user-images.githubusercontent.com/61884887/175801952-eda01a4c-a9ed-428f-bfba-92e5bfe96560.png)
Test with [new schema](https://raw.githubusercontent.com/ansible/schemas/main/f/ansible.json)
![with_new](https://user-images.githubusercontent.com/61884887/175801955-10f45a1f-217d-4756-a6cc-951cdfc5279b.png)

**Comment by ssbarnea** [comment]
Not having items is perfectly valid and current version of the schema does pass  https://www.jsonschemavalidator.net/ tests. In fact we do have two schema validators as part of our CI integration so I think that the chance of merging a broken schema is quite low.

**Comment by zach-source** [comment]
Okay. Thanks @ssbarnea for looking at it. I'll just maintain a fork for my purposes.
