### ISSUE TITLE
Custom become_method

### ISSUE THREAD

**Issue by internetionals** [ansible/schemas#336]
I'm getting ansible-lint schema validation errors on some of our playbooks where we're using a customer become-plugin:

```txt
schema: 'mydo' is not one of ['sudo', 'su', 'pbrun', 'pfexec', 'runas', 'dzdo', 'ksu', 'doas', 'machinectl'] (schema[tasks])
```

We've currently worked around these validation issues by using a jinja template as an escape hatch:

```yaml:
task:
   become_method: "{{ 'mydo' }}"
```

But this feels clunky and unnecessary. What would be a better way to support become-plugins? I suspect simply changing to be anything is not in line with this project (though it is a fully dynamically chosen value). Pherhaps something like allowing all FCQN references? (haven't tried those, our current plugin is not in a collection yet, but that should be possible)

**Comment by ssbarnea** [comment]
@cidrblock WFYT about this? Which approach should we take?

**Comment by ssbarnea** [comment]
I think that the current workaround can be considered a good compromise for keeping the ability to suggest the default become methods. If others report it as problematic we might consider a different approach or at least to document it in field description.
