### ISSUE TITLE
Galaxy schema does not support PEP 440 pre-relase version specs

### ISSUE THREAD

**Issue by juanvalino** [ansible/schemas#340]
Currently `schema[galaxy]` does not support pre-relases version format described in [PEP 440 – Version Identification and Dependency ](https://peps.python.org/pep-0440/).

For example, if you set the following `galaxy.yml`:

```
namespace: mynamespace
name: mycollection
version: 1.0.0a27
readme: README.md
authors:
  - author name
description: collection description
license:
  - GPLv3
  - EUPL
license_file: LICENSE
tags: []
dependencies: {}
build_ignore: []
```

you get the following error because regex pattern doesn't cover PEP 440 pre-relaseses specs:

```
schema: '1.0.0a27' does not match '^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9
    ]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-
    9a-zA-Z-]+)*))?$' (schema[galaxy])
```

**Comment by ssbarnea** [comment]
I was aware about that but at the same time, we need some references to either galaxy or automation hub to fix this properly. 

I was not able to find any documentation mentioning that versioning on galaxy or hub needs to follow Python PEP-440 format. In the end, they are not python packages.

**Comment by ssbarnea** [comment]
By reading https://galaxy.ansible.com/docs/contributing/version.html I can assume that galaxy aims to support only https://semver.org/ specification and not the PEP-440 format.

That spec also has sample regexes for checking it, so it might be possible that we will refuse this change.

I already contacted galaxy team for commenting as I do want some feedback from them first.

AFAIK, semver is a little bit more restrictive than PEP-440 but also compatible. Still not every PEP-440 version is a valid semver. If that is confirmed maybe we need to improve documentation about accepted version formats.

**Comment by sivel** [comment]
> By reading https://galaxy.ansible.com/docs/contributing/version.html I can assume that galaxy aims to support only https://semver.org/ specification and not the PEP-440 format.

This information is correct. pep440 is invalid for collection versioning.  We only support semver for collection versioning.
