### ISSUE TITLE
Is there a reason for not allowing numbers in collection names?

### ISSUE THREAD

**Issue by timo-fc** [ansible/schemas#369]
Hi,
collections names in the meta/main.yml are currently not allowed to contain numbers.
But there are collections with numbers in specially the namespace part.

Are there any rules about it which I'm not aware of or should the schemata be changed?

**Comment by ssbarnea** [comment]
The current pattern is `"[a-z][a-z0-9_]+"` which does allow use of numbers, while matching the requirements for publishing.

You cannot start with a number, but you can have number inside.
