### ISSUE TITLE
Ansible galaxy enforces use of `repository` key

### ISSUE THREAD

**Issue by mnaser** [ansible/schemas#397]
The project does not have `repository` listed as a required key, however, imports to Galaxy will fail if that's missing.

Should that be set to a required value or is that purposely left out?

**Comment by ssbarnea** [comment]
Which schema galaxy or meta? meta one is very tricky but for the other one it should be fixable.

**Comment by mnaser** [comment]
@ssbarnea this is for `galaxy.yml`, it is required for a successful import of a collection into galaxy
