### ISSUE TITLE
Molecule schema: Missing properties on PlatformModel

### ISSUE THREAD

**Issue by frabar** [ansible/schemas#83]
![TT_MoleculePlatformModel](https://user-images.githubusercontent.com/15174375/127173649-6a7f9e74-8433-42a2-91fe-1e2d4d78092a.png)
Molecule schema is missing `pre_build_image` and `env`.

see also:
https://github.com/ansible-community/molecule/blob/master/src/molecule/model/schema_v3.py

**Comment by ssbarnea** [comment]
That is a property specific to docker/podman containers, molecule itself does not know about it. Addressing these will be bit tricky as drivers do have lots of custom options.

I am not closing it because I still consider it a valid bug, is only one that is not so easy to address.

**Comment by DanSibbernsen** [comment]
@ssbarnea I'm guessing the pre_build_image part of this issue has been resolved. See [0e5859fe](https://github.com/ansible-community/schemas/commit/0e5859fe8115222dafdc9ad13569ac0d38e7c72a) for the resolution.

Is that commit a good way to model the "env" fix? If so, I might take a swing at it this weekend.
